### ISSUE TITLE
[User Story 1] User permissions for counter

### ISSUE THREAD

**Issue by GigiLoria5** [ciaccogiuseppe/se2022-08-OfficeQueueManager#1]
At present, I have not yet managed privilege control for the creation and deletion of a counter (I would say only a manager), as server-side authentication has not yet been implemented. But the question is whether it actually makes sense to do so or not

**Comment by ciaccogiuseppe** [comment]
At the moment I think we should not consider authentication issues either by hardcoding the logged in manager or by not considering authentication in the first implementation

**Comment by GigiLoria5** [comment]
so server-side authentication will not be handled (via passport)?

**Comment by ciaccogiuseppe** [comment]
If user authentication will not be implemented in the needed time, we will do like that, otherwise we can handle it while merging branches
