### ISSUE TITLE
Unit/Integration Testing

### ISSUE THREAD

**Issue by GigiLoria5** [ciaccogiuseppe/se2022-08-OfficeQueueManager#2]
I started thinking about the testing part, and ended up with the thought that maybe we have practically no unit testing. Our server-side architecture is practically two-tiered (api using make calls to dao), and there are practically no isolated functions.
At ''good'' soft eng 1, they made us do unit testing of the dao, but that is not correct because they have a database dependency anyway [(Unit Tests DAO are waste).](https://www.petrikainulainen.net/programming/testing/writing-tests-for-data-access-code-unit-tests-are-waste/)
So, in my opinion, on the server side we simply have to do API testing (== integration of the API calls) and if there is any function worth testing with unit.
Tell me what you think.

**Comment by ciaccogiuseppe** [comment]
For sure we'll have unit tests on the time estimation function
For the other parts I agree with you about dao testing not being unit test (if we don't use a dB mockup of course which not something we need I think), we can consider dao testing and integration testing or just integration testing

**Comment by GigiLoria5** [comment]
Yes exactly... but there will be maybe 1/2/3 functions in the entire project that need unit tests... this is a problem we didn't think during planning and so we have now some problems... for example I have one task of 3h3m of unit testing of 1 function and I think it will be very far from the truth. 
As I said before, for our architectural structure of the back end, we could just do integration (api testing especially) and as u said only unit testing of what can be tested in isolation.

**Comment by ciaccogiuseppe** [comment]
Yeah the 3h30m one is about time estimation function which has some boundary conditions and special cases to test. We will actually see how much it will take.
For the other ones I agree they could be included in integration so unit test tasks will probably be overestimated, which could not be a great problem since we are working more than expected on general setup
