### ISSUE TITLE
Service APIs documentation

### ISSUE THREAD

**Issue by GigiLoria5** [ciaccogiuseppe/se2022-08-OfficeQueueManager#5]
I notice that in our documentation (README.md) the descriptions of the GET route _/api/service/:id_ is missing. When you can, please add it, so I can test everything 🙂

**Comment by FedeBel** [comment]
ok, i update the README.md with the GET route /api/service/:id, both on the dev and in my branch (FedeBel_feature_add-service-backend)

**Comment by GigiLoria5** [comment]
@FedeBel there are still some problems in the documentation so I'll suggest you to review each api calls in the documentation. For example one "error" I found is in POST /api/service: in the documentation the name is not needed but then in the route/db you request also a name. Due to the database structure I decided to leave the name in the tests because I think the error is in the documentation, otherwise you are allowed to edit the test file (if you also edit the db and the route code)
![immagine](https://user-images.githubusercontent.com/41837640/196760178-6dfe494f-fca3-4a47-ad43-f6053e849043.png)

**Comment by FedeBel** [comment]
yeah the documentation inside the FedeBel_feature_add-service-backend is not updated. I updated the documentation inside the branch test and branch dev.
