### ISSUE TITLE
Ticket in db table

### ISSUE THREAD

**Issue by ciaccogiuseppe** [ciaccogiuseppe/se2022-08-OfficeQueueManager#6]
I'm working on the APIs for ticket and I can't figure out the difference between ID_Ticket and numTicket. How should I handle them correctly?

**Comment by FedeBel** [comment]
The ID_Ticket is unique for every type of service, instead numTicket is a number for a specific service. For example there might be the ticket 2 for Service 1 and the ticket 2 for Service 2

**Comment by FedeBel** [comment]
For example in a post office there might be the ticket 2 for "paying bills" and ticket 2 for "pick up a package"

**Comment by ciaccogiuseppe** [comment]
Ok, I get it. Still don't know if it's something we actually need since it can be computed as a COUNT(*) if needed, while it could be a problem in inserting values in the table

**Comment by FedeBel** [comment]
Ok you're right, i delete the field numTicket. I see on youtrack that the part of API frontend about the ticket is in the open phase, so i think that it is not a problem if i delete the field now.

**Comment by ciaccogiuseppe** [comment]
Yes I think it's the best solution, it should not be a problem for other parts of the code since at the moment I'm the only one working on it
